movieproject/movieapp/urls.py
from . import views
from django.urls import path

app_name = 'movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movies/<int:movie_id>/',views.detail,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from . models import Movie
from . forms import MovieForm


# Create your views here.
def index(request):
    # return HttpResponse("am index")
    movies = Movie.objects.all()
    context = {
        'movie_list' : movies
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie_details = Movie.objects.get(id = movie_id)
    # return HttpResponse("This is movie no : %s" % movie_id)
    return render(request,'detail.html',{'movie':movie_details})

def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<div class="container" style="margin: 20px">
     <h2 style="color: blue;">Add Movie</h2>
    <div class="row">
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="name" placeholder="Enter Movie Name" style="margin: 20px"><br>
        <input type="text" name="desc" placeholder="Movie Description" style="margin: 20px"><br>
        <input type="text" name="year" placeholder="Movie Year" style="margin: 20px"><br>
        <input type="file" name="img" style="margin: 20px"><br>
        <input class="btn btn-primary" type="submit" style="margin: 20px" value="Add">
        </form>
    </div>

</div>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- adding nav bar -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

      Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <h5>Are you sure want to delete this movie ..?</h5>
    <input type="submit" class="btn btn-danger" value="Delete">
</form>
{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="margin: 20px">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" height="300" width="300"><br>
        </div>
        <div class="col-md-6">
           <h2>{{movie.name}}</h2> <br>
            <h5>{{movie.desc}}</h5><br>
            <h6>{{movie.year}}</h6><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>



{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="margin: 20px">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" class="btn btn-primary">
    </form>
</div>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<a class="btn btn-primary" href="{% url 'movieapp:add_movie' %}" style="margin: 10px;">Add Movies</a>
<div class="container">
    <div class="row">
        {% for i in movie_list %}
            <div class="col-md-3">
                <div class="card">
                    <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250px">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
<!--                        <p class="card-text">{{i.desc}}</p>-->
                        <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Go to more</a>
                    </div>
                </div>
            </div>
         {% endfor %}
    </div>
</div>
{% endblock %}